name: Continous Integration

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - 'History.md'
      - 'README.md'

env:
  GOLANGCILINT_VERSION: "1.63.4"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-with-vips: [
          "alpine3-14.vips8-10-6",
          "alpine3-16.vips8-12-2",
          "alpine3-17.vips8-13-3",
          "alpine3-18.vips8-14-3",
          "alpine3-21.vips8-15-3"
        ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max`
          load: true
          build-args: |
            GOLANGCILINT_VERSION=${{ env.GOLANGCILINT_VERSION }}
          file: Dockerfile.${{ matrix.container-with-vips }}
          tags: h2non/bimg:ci-${{ matrix.container-with-vips }}

      - name: Run tests
        run: |
          docker run --rm -v $PWD:/build h2non/bimg:ci-${{ matrix.container-with-vips }} sh -c 'cd /build && go vet . && golangci-lint run && go test -v -race -covermode=atomic -coverprofile=coverage.out'
